version: '3.8'

services:
    database:
        container_name: banker-postgres
        image: postgres:15.2
        ports:
            - '${DB_PORT}:${DB_PORT}'
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}
        healthcheck:
            test: 'exit 0'
        volumes:
            - database:/var/lib/postgresql/data
    migration:
        container_name: banker-migrations
        depends_on:
            database:
                condition: service_healthy
        image: liquibase/liquibase:4.20.0
        volumes:
            - ./src/database/migrations:/liquibase/changelog
        command:
            'update --username=${DB_USERNAME} --password=${DB_PASSWORD} --url=${DB_MIGRATION_URL} --liquibase-schema-name=public
            --changelogFile="./master.json"'
    prometheus:
        container_name: banker-prometheus
        image: prom/prometheus
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus-storage:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        ports:
            - '${APP_PROMETHEUS_PORT}:${APP_PROMETHEUS_PORT}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'

volumes:
    prometheus-storage:
    database:
