scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:${APP_PORT}']
        labels:
          service: 'prisma-metrics'
          group: 'production'
